# Generated by Django 3.1.12 on 2025-09-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scra_tool', '0002_auto_20250927_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
