# Generated by Django 3.1.12 on 2025-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scra_tool', '0003_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extra_off', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp', models.CharField(blank=True, max_length=50, null=True)),
                ('offer', models.CharField(blank=True, max_length=255, null=True)),
                ('protect_info', models.JSONField(blank=True, null=True)),
                ('ratings_reviews', models.JSONField(blank=True, null=True)),
                ('coupons', models.JSONField(blank=True, null=True)),
                ('bank_offers', models.JSONField(blank=True, null=True)),
                ('purchase_options', models.JSONField(blank=True, null=True)),
                ('color_options', models.JSONField(blank=True, null=True)),
                ('storage_options', models.JSONField(blank=True, null=True)),
                ('ram_options', models.JSONField(blank=True, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_note', models.TextField(blank=True, null=True)),
                ('payment_offers', models.JSONField(blank=True, null=True)),
                ('seller_info', models.JSONField(blank=True, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('question_answer', models.JSONField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('product_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
