# Generated by Django 5.2.6 on 2025-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scra_tool', '0004_product_bank_offers_product_color_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
