# Generated by Django 5.2.6 on 2025-09-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scra_tool', '0005_product_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
