# Generated by Django 5.2.5 on 2025-09-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scra_tool', '0007_product_description_product_extra_off_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
