# Generated by Django 5.2.5 on 2025-09-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scra_tool', '0008_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extra_off', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('mrp', models.CharField(blank=True, max_length=100, null=True)),
                ('offer', models.CharField(blank=True, max_length=255, null=True)),
                ('protect_info', models.TextField(blank=True, null=True)),
                ('ratings_reviews', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_offers', models.JSONField(blank=True, null=True)),
                ('purchase_options', models.JSONField(blank=True, null=True)),
                ('color_options', models.JSONField(blank=True, null=True)),
                ('storag_options', models.JSONField(blank=True, null=True)),
                ('ram_options', models.JSONField(blank=True, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_note', models.TextField(blank=True, null=True)),
                ('payment_offers', models.JSONField(blank=True, null=True)),
                ('highlight_items', models.JSONField(blank=True, null=True)),
                ('seller_info', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_description', models.JSONField(blank=True, null=True)),
                ('specifications', models.JSONField(blank=True, null=True)),
                ('question_answer', models.JSONField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('product_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
