# Generated by Django 5.2.5 on 2025-09-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scra_tool', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bank_offers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
