# Generated by Django 5.2.5 on 2025-09-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scra_tool', '0010_alter_product_bank_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bank_offers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
